# Consul configuration goes in this task
# Source: https://learn.hashicorp.com/tutorials/vault/deployment-guide
- name: create vault group
  group:
    name: "{{ vault_group }}"
    state: "present"

- name: create vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    state: "present"
    system: "yes"
    comment: "{{ vault_user }} nologin user"
    createhome: "no"

- name: setup vault configuration directory
  file:
    path: "{{ vault_dir }}"
    mode: "0644"
    owner: "vault"
    group: "vault"
    state: "directory"

- name: install vault
  apt:
    name: vault
    state: present

- name: configure config.hcl file
  template:
    src: "config.hcl.j2"
    mode: "0644"
    dest: "{{ vault_dir }}/config.hcl"
    owner: "vault"
    group: "vault"

- name: configure systemd for vault
  template:
    src: "vault.service.j2"
    mode: "0644"
    dest: "/etc/systemd/system/vault.service"
    owner: "root"
    group: "root"

- name: ensure vault service is started at boot
  service:
    name: "vault"
    state: "started"
    enabled: "yes"
 
- name: set global variables
  copy:
    dest: "/etc/profile.d/vault_addr.sh"
    content: |
      export VAULT_ADDR="localhost:8200"
