---
- name: setup vault certificates directory
  file:
    path: "{{ vault_certs_dir }}"
    owner: "root"
    group: "root"
    mode: '0755'
    state: "directory"

- name: setup vault ssl certificate
  block:
    - name: Create CA root key
      shell: |
        KEY="{{ vault_certs_dir }}/vault-ca.key"
        openssl genrsa -out "$KEY" 4096

    - name: Create and self sign the root certificate
      shell: |
        KEY="{{ vault_certs_dir }}/vault-ca.key"
        CRT="{{ vault_certs_dir }}/vault-ca.crt"
        ST="California"
        O="Epicgames"
        CN="localhost"
        SUBJ="/C=US/ST=$ST/O=$O/CN=$CN"
        openssl req -new -x509 -days 365 -key "$KEY" \ 
        -subj "$SUBJ" -out "$CRT"

    - name: Create CSR for vault
      shell: |
        KEY="{{ vault_certs_dir }}/vault.key"
        CSR="{{ vault_certs_dir }}/vault.csr"
        ST="California"
        O="Epicgames"
        CN="localhost"
        SUBJ="/C=US/ST=$ST/O=$O/CN=$CN"
        openssl req -new -sha256 -key "$KEY" -subj "$SUBJ" -out "$CSR"

    - name: Generate vault certificate
      shell: |
        echo "subjectAltName=DNS:localhost" > SAN.txt
        CRT="{{ vault_certs_dir }}/vault-ca.crt"
        CSR="{{ vault_certs_dir }}/vault.csr"
        KEY="{{ vault_certs_dir }}/vault-ca.key"
        VAULT_CRT="{{ vault_certs_dir }}/vault.crt"
        openssl x509 -req -extfile SAN.txt -days 365 -in "$CSR" -CA "$CRT" \ 
        -CAkey "$KEY" -CAcreateserial -out "$VAULT_CRT"

- name: change vault certificate ownership
  file:
    path: "{{vault_certs_dir}}/vault.crt"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: change ca certificate ownership
  file:
    path: "{{vault_certs_dir}}/vault-ca.crt"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: change private key ownership
  file:
    path: "{{vault_certs_dir}}/vault.key"
    owner: 'root'
    group: 'vault'
    mode: '0640'

- name: copy CA cert  to ca-certificate folder
  copy:
    src: "{{ vault_certs_dir }}/vault-ca.crt"
    dest: "/usr/local/share/ca-certificates/"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: update CA certificates
  shell: update-ca-certificates

